name: integration

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  install-production:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    
    strategy:
      matrix:
        runtime: [node, nsolid]
        node-version: [16, 18, 20]
        os: [ubuntu-latest]
        pnpm-version: [8]
        include:
          - runtime: nsolid
            nsolid-version: 5
          - runtime: node
            node-version: 14
            os: ubuntu-latest
            pnpm-version: 7
        exclude:
          - runtime: nsolid
            node-version: 16


    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Use Node.js
        if: ${{ matrix.runtime == 'node'}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: nodesource/setup-nsolid@v1
        if: ${{ matrix.runtime == 'nsolid'}}
        with:
          node-version: ${{ matrix.node-version }}
          nsolid-version: ${{ matrix.nsolid-version }}

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Install Production
        run: |
          pnpm install --prod

      - name: Run server
        run: |
          node integration/server.js &

      - name: Test
        if: ${{ success() }}
        run: |
          bash integration/test.sh
